collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

title: title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: https://frolovanatolui.github.io/
baseurl: stepByStepJekyll/
twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
